[project]
name = "agente-operador"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Antonio E.", email = "125406609+antoniosdet@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
agente-operador = "agente_operador:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
